version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf 

  frontend:
    container_name: frontend
    image: tmarshqa/frontend
    build: ./frontend

  backend:
    container_name: backend
    image: tmarshqa/backend
    build: ./backend


  db:
    container_name: mysql
    image: tmarshqa/db
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: users
    volumes:
    - type: volume
      source: db-volume
      target: /var/lib/mysql
volumes:
  db-volume: